# Generated by Django 6.0.8 on 2026-09-13 13:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news_covers/",
                validators=[core.validators.MaxFileSizeValidator(5)],
            ),
        ),
    ]
