# Generated by Django 6.0.8 on 2026-09-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamekey",
            options={
                "ordering": ["pk"],
                "permissions": [("reveal_key", "Can reveal a game key's plaintext")],
            },
        ),
        migrations.AlterModelOptions(
            name="inventoryimportbatch",
            options={
                "ordering": ["-created_at"],
                "permissions": [("import_inventory", "Can import game key inventory")],
            },
        ),
        migrations.AlterModelOptions(
            name="marketplacesettings",
            options={
                "permissions": [
                    ("toggle_killswitch", "Can toggle marketplace kill switches"),
                    ("view_dashboard", "Can view the marketplace admin dashboard"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("fulfill_order", "Can manually re-drive order fulfilment"),
                    ("refund_order", "Can initiate or approve order refunds"),
                ],
            },
        ),
    ]
