# Generated by Django 6.0.8 on 2026-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_ratelimitcounter"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplacesettings",
            name="paypal_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketplacesettings",
            name="stripe_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="attempt",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="payment",
            name="checkout_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="payment",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="failure_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("order", "attempt"), name="uniq_payment_order_attempt"
            ),
        ),
    ]
