# Generated by Django 6.0.8 on 2026-09-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_payment_attempts_and_provider_switches"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
