# Generated by Django 6.0.8 on 2026-09-21 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_refund_data(apps, schema_editor):
    Refund = apps.get_model("marketplace", "Refund")
    Payment = apps.get_model("marketplace", "Payment")
    Refund.objects.filter(provider_refund_id="").update(provider_refund_id=None)
    for payment in Payment.objects.filter(refunds__status="completed").distinct():
        total = sum(
            payment.refunds.filter(status="completed").values_list("amount_minor", flat=True)
        )
        Payment.objects.filter(pk=payment.pk).update(
            refunded_minor=min(total, payment.amount_minor)
        )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("marketplace", "0008_payment_reconciled_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=32)),
                ("provider_dispute_id", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=128)),
                ("amount_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("response_due_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_minor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="refund",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="refund",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="refund",
            name="provider_status",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="refund",
            name="source",
            field=models.CharField(
                choices=[("admin", "Admin"), ("provider", "Provider")],
                default="admin",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="provider_refund_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(backfill_refund_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("refunded_minor__lte", models.F("amount_minor"))),
                name="payment_refunded_not_above_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                fields=("payment", "provider_refund_id"), name="uniq_refund_payment_provider_id"
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="marketplace.order",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes",
                to="marketplace.payment",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispute",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_dispute_id"), name="uniq_dispute_provider_id"
            ),
        ),
    ]
