# Generated by Django 6.0.8 on 2026-08-27 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_missing_profile_website'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="profile",
                    name="created_at",
                    field=models.DateTimeField(
                        auto_now_add=True,
                        default=django.utils.timezone.now,
                    ),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name="profile",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AddField(
                    model_name="profile",
                    name="website",
                    field=models.URLField(blank=True),
                ),
                migrations.AlterField(
                    model_name="profile",
                    name="discord_username",
                    field=models.CharField(blank=True, max_length=64),
                ),
                migrations.AlterField(
                    model_name="profile",
                    name="psn_id",
                    field=models.CharField(blank=True, max_length=64),
                ),
                migrations.AlterField(
                    model_name="profile",
                    name="steam_id",
                    field=models.CharField(blank=True, max_length=64),
                ),
            ],
        ),
    ]
