# Generated by Django 6.0.8 on 2026-09-13 13:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profilegame"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[core.validators.MaxFileSizeValidator(5)],
            ),
        ),
    ]
