# Generated by Django 6.0.8 on 2026-09-13 13:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="game_covers/",
                validators=[core.validators.MaxFileSizeValidator(5)],
            ),
        ),
    ]
