# Generated by Django 6.0.8 on 2026-09-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_alter_game_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_verified_purchase",
            field=models.BooleanField(default=False),
        ),
    ]
