# Generated by Django 6.0.8 on 2026-09-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("new_follower", "New Follower"),
                    ("thread_reply", "Thread Reply"),
                    ("dm_received", "Dm Received"),
                    ("reaction_received", "Reaction Received"),
                    ("badge_earned", "Badge Earned"),
                    ("order_fulfilled", "Order Fulfilled"),
                    ("order_needs_review", "Order Needs Review"),
                ],
                max_length=20,
            ),
        ),
    ]
